<?php
/**
 * Created by PhpStorm.
 * User: Tanguy
 * Date: 03/01/2019
 * Time: 17:37
 */

namespace App\Model\Table;


use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Localized\Validation\FrValidation;
use Cake\ORM\Rule\IsUnique;
use Cake\ORM\RulesChecker;

class AdherentsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->hasMany('Factures', [
            'dependent' => true,
            'cascadeCallbacks' => true,
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->requirePresence(['nom', 'prenom', 'tel', 'mail', 'dateNaissance', 'handicap', 'licence'], 'create')
            ->setProvider('fr', FrValidation::class)
            ->add('tel', 'myCustomRuleNameForPhone', [
                'rule' => 'phone',
                'provider' => 'fr',
            ])
            ->add('mail', 'valid', [
                'rule' => 'email',
                'message' => 'Email invalide'
            ]);
        return $validator;
    }

    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['mail'], 'Mail déjà utilisé'));
        $rules->add($rules->isUnique(['mailTuteur'], 'Mail déjà utilisé'));
        $rules->add($rules->isUnique(['tel'], 'Téléphone déjà utilisé'));
        $rules->add($rules->isUnique(['telTuteur'], 'Téléphone déjà utilisé'));
        return parent::buildRules($rules); // TODO: Change the autogenerated stub
    }

}