<?php
/**
 * Created by PhpStorm.
 * User: p1701300
 * Date: 19/12/2018
 * Time: 16:32
 */

namespace App\Model\Table;


use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Localized\Validation\FrValidation;
use Cake\ORM\Rule\IsUnique;
use Cake\ORM\RulesChecker;

class EstablishmentsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);
        $this->hasMany('Adherents');
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->requirePresence(['nom', 'adresse', 'codePostal', 'ville', 'nomDirecteur', 'tel'], 'create')
            ->setProvider('fr', FrValidation::class)
            ->add('codePostal', 'myCustomRuleNameForPostal', [
                'rule' => 'postal',
                'provider' => 'fr',
            ])
            ->add('tel', 'myCustomRuleNameForPhone', [
                'rule' => 'phone',
                'provider' => 'fr',
            ]);

        return $validator;
    }

    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['nom'], 'Etablissement déjà existant'));
        $rules->add($rules->isUnique(['tel'], 'Téléphone déjà utilisé'));
        return parent::buildRules($rules); // TODO: Change the autogenerated stub
    }


}