<?php
/**
 * Created by PhpStorm.
 * User: Tanguy
 * Date: 03/01/2019
 * Time: 13:30
 */

namespace App\Model\Table;


use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Localized\Validation\FrValidation;
use Cake\ORM\Rule\IsUnique;
use function Sodium\add;

class UsersTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->requirePresence(['nom', 'prenom', 'password', 'tel', 'mail', 'confirm_password'], 'create')
            ->setProvider('fr', FrValidation::class)
            ->add('tel', 'myCustomRuleNameForPhone', [
                'rule' => 'phone',
                'provider' => 'fr',
                'message' => 'Numéro invalide',
            ])
            ->add('mail', 'valid', [
                'rule' => 'email',
                'message' => 'Email invalide'
            ])
            ->add('confirm_password', 'no-misspelling', [
                'rule' => ['compareWith', 'password'],
                'message' => 'Les mots de passe ne sont pas égaux',
            ]);
        return $validator;
    }

    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['mail'], 'Mail déjà utilisé'));
        $rules->add($rules->isUnique(['tel'], 'Téléphone déjà utilisé'));
        return parent::buildRules($rules); // TODO: Change the autogenerated stub
    }


}